wrapper update

diff --git a/archuseriso b/archuseriso
--- a/archuseriso
+++ b/archuseriso
@@ -1,28 +1,125 @@
-#!/bin/sh
+#!/bin/bash
+
+version=0.2.1
+confdir=/usr/share/archiso/configs
+config=
+options=
 
 _usage () {
-    echo "usage:" 
-    echo "archuseriso console [options]"
-    echo "archuseriso gnome [options]"
-    echo "archuseriso kde [options]"
+    echo "archuseriso v${version} usage:"
+    echo
+    echo "archuseriso <iso config> [-C|--config <path>] [build options]"
+    echo
+    echo "help:"
+    echo "archuseriso -h"
+    echo
+    echo "iso config help:"
+    echo "archuseriso <iso config> -h"
+    echo
+    echo "iso config list, select one from:"
+    echo "* console"
+    echo "* gnome"
+    echo "* kde"
+    echo
+    echo "Build examples:"
+    echo "archuseriso kde"
+    echo "archuseriso kde -l fr"
     exit ${1}
 }
 
+_help () {
+    echo "The archuseriso program is a wrapper"
+    echo "which executes the corresponding iso"
+    echo "config's build script."
+    echo "You may directly run the config's"
+    echo "script \`build.sh\` instead."
+    echo
+    echo "Synopsis:"
+    echo "archuseriso <iso config> [-C|--config <path>] [build options]"
+    echo
+    echo "-C, --confdir <path>"
+    echo "    Path to configs directory (default: /usr/share/archiso/configs)"
+    echo
+    echo "iso config list, select one from:"
+    echo "* console"
+    echo "* gnome"
+    echo "* kde"
+    echo
+    echo "Build examples:"
+    echo "archuseriso kde"
+    echo "archuseriso kde -l fr"
+    echo
+    echo "To list the build script options:"
+    echo "archuseriso <iso config> -h"
+    echo
+    echo "or run the config's build script:"
+    echo "<path>/build.sh -h"
+    echo
+    echo "To customize an iso config:"
+    echo "cp -rL /usr/share/archiso/configs/<config> <destination>"
+    echo
+    echo "Customize your config then run the config's \`build.sh\` script."
+    exit ${1}
+}
+
+
 if [[ ${EUID} -ne 0 ]]; then
     echo "This script must be run as root."
-    _usage 1
+    echo
+    echo "help:"
+    echo "archuseriso -h"
+    exit 1
 fi
 
-case "${1}" in
-    console|Console)
-        shift
-        /usr/share/archiso/configs/console/build.sh $@;;
-    gnome|Gnome)
-        shift
-        /usr/share/archiso/configs/gnome/build.sh $@;;
-    kde|Kde)
-        shift
-        /usr/share/archiso/configs/kde/build.sh $@;;
+if [[ "$1" == '-h' ]]; then
+  _help 0
+fi
+
+case "$1" in
+    console)
+        config="console"
+        shift ;;
+    gnome)
+        config="gnome"
+        shift ;;
+    kde)
+        config="kde"
+        shift ;;
     *)
-        _usage 1;;
+        _usage 1 ;;
 esac
+
+OPTS=$(getopt -o 'A:C:D:L:N:P:V:hl:o:g:w:v' --long 'confdir:,help' -n 'archuseriso' -- "$@")
+eval set -- "${OPTS}"
+
+[[ "$?" -eq 0 ]] || _usage 1
+unset OPTS
+
+while true; do
+    case "$1" in
+        '-C'|'--confdir')
+            confdir="$2"
+            shift 2 ;;
+        '-A'|'-D'|'-L'|'-N'|'-P'|'-V'|'-l'|'-o'|'-g'|'-w')
+            options+="$1 $2 "
+            shift 2 ;;
+        '-h'|'--help')
+            options="-h"
+            shift
+            break ;;
+        '-v')
+            options+="-v "
+            shift ;;
+        '--')
+            shift
+            break ;;
+        *)
+            shift
+            echo "Invalid argument ${arg}"
+            _usage 1 ;;
+    esac
+done
+
+# Run the build script:
+echo "${confdir}/${config}"/build.sh "${options}"
+eval "${confdir}/${config}/build.sh ${options}"
