aui-mkpersistent new encryption option
* LUKS encryption option for persistent partition

diff --git a/aui-mkiso b/aui-mkiso
--- a/aui-mkiso
+++ b/aui-mkiso
@@ -1,68 +1,101 @@
 #!/bin/bash
 
-version=0.3.3
+set -e -u
+
 confdir=/usr/share/archiso/configs
 config=
 options=
 
 _usage () {
     echo
-    echo "aui-mkiso v${version} usage:"
+    echo 'aui-mkiso, Live ISO image build.'
     echo
-    echo "aui-mkiso <iso config> [-C|--config <path>] [build options]"
+    echo 'Command synopsis:'
+    echo 'aui-mkiso <iso config> [options] [build options]'
     echo
-    echo "help:"
-    echo "aui-mkiso -h"
+    echo 'To get help run:'
+    echo 'aui-mkiso --help'
     echo
-    echo "iso config help:"
-    echo "aui-mkiso <iso config> -h"
-    echo
-    echo "iso config list, select one from:"
-    echo "console, cinnamon, deepin, gnome, kde, mate, xfce"
-    echo
-    echo "Build examples:"
-    echo "aui-mkiso kde"
-    echo "aui-mkiso kde -l fr"
     exit ${1}
 }
 
 _help () {
     echo
-    echo "aui-mkiso is a wrapper which runs the"
-    echo "corresponding iso config's build script."
-    echo "You may directly run the config's"
-    echo "build script \`build.sh\`."
+    echo 'Archuseriso tool for building a custom Arch Linux Live ISO image.'
     echo
-    echo "Synopsis:"
-    echo "aui-mkiso <iso config> [-C|--config <path>] [build options]"
+    echo 'Command synopsis:'
+    echo 'aui-mkiso <iso config> [options] [build options]'
     echo
-    echo "-C, --confdir <path>"
-    echo "    Path to configs directory (default: /usr/share/archiso/configs)"
+    echo 'Options:'
+    echo '-h, --help           command help'
+    echo '-C, --configs-path   path to directory configs'
+    echo '                     default: /usr/share/archiso/configs'
     echo
-    echo "iso config list, select one from:"
-    echo "console, cinnamon, deepin, gnome, kde, mate, xfce"
+    echo "Config's specific help:"
+    echo 'aui-mkiso <iso config> -h | --help'
     echo
-    echo "Build examples:"
-    echo "aui-mkiso kde"
-    echo "aui-mkiso kde -l fr"
+    echo 'Configs list, select one from:'
+    echo 'console, cinnamon, deepin, gnome, kde, mate, xfce'
     echo
-    echo "To list the build script options:"
-    echo "aui-mkiso <iso config> -h"
+    echo 'Build example:'
+    echo 'sudo aui-mkiso xfce'
     echo
-    echo "or run the config's build script:"
-    echo "<path>/build.sh -h"
+    echo 'To customize a config, copy a config to your working directory:'
+    echo 'cp -LrT /usr/share/archiso/configs/<config> [path/]<config> 2> /dev/null'
+    echo 'cp -rT /usr/share/archiso/aui [path/]<config>/aui'
     echo
-    echo "To customize an iso config:"
-    echo "cp -rL /usr/share/archiso/configs/<config> <destination>"
+    echo 'Example, copy xfce config to home subdir sources:'
+    echo 'cp -LrT /usr/share/archiso/configs/xfce ~/sources/xfce 2> /dev/null'
+    echo 'cp -rT /usr/share/archiso/aui ~/sources/xfce/aui'
     echo
-    echo "Edit package lists located in <config> and <config>/lang/<locale>."
-    echo "Add your pre-built AUR packages to <config>/pkglocal."
-    echo "Then run the config's build script \`build.sh\`."
+    echo 'Edit the packages*.x86_64 files located in ~/sources/xfce and'
+    echo '~/sources/xfce/lang'.
+    echo
+    echo 'Optionnally add your own pre-built AUR binary packages to ~/sources/xfce/pkglocal'
+    echo
+    echo 'To build your customized iso use the --configs-path command option:'
+    echo 'sudo aui-mkiso xfce --configs-path ~/sources'
+    echo
     exit ${1}
 }
 
+OPTS=$(getopt -o 'A:C:D:L:N:P:V:c:g:hl:o:w:v' --long 'configs-path:,help' -n 'aui-mkiso' -- "$@")
+[[ $? -eq 0 ]] || _usage 1
+eval set -- "${OPTS}"
+unset OPTS
+[[ $# -eq 1 ]] && _usage 0
 
-if [[ ${EUID} -ne 0 ]]; then
+while true; do
+    case "$1" in
+        '-C'|'--configs-path')
+            confdir="$2"
+            shift 2 ;;
+        '-A'|'-D'|'-L'|'-N'|'-P'|'-V'|'-c'|'-g'|'-l'|'-o'|'-w')
+            options+="$1 $2 "
+            shift 2 ;;
+        '-h'|'--help')
+            options="-h "
+            shift ;;
+        '-v')
+            options+="-v "
+            shift ;;
+        '--')
+            shift
+            break ;;
+    esac
+done
+
+[[ $# -eq 0 ]] && [[ "${options}" =~ '-h' ]] && _help 0
+[[ $# -eq 1 ]] || { echo 'Error: invalid arguments!'; _usage 1; }
+
+case $1 in
+    cinnamon | console | deepin | gnome | kde | mate | xfce)
+        config=$1 ;;
+    *)
+        _usage 1 ;;
+esac
+
+if [[ ! "${options}" =~ '-h' && ${EUID} -ne 0 ]]; then
     echo "This script must be run as root."
     echo
     echo "help:"
@@ -70,66 +103,5 @@ if [[ ${EUID} -ne 0 ]]; then
     exit 1
 fi
 
-if [[ "$1" == '-h' ]]; then
-  _help 0
-fi
-
-case "$1" in
-    console)
-        config="console"
-        shift ;;
-    cinnamon)
-        config="cinnamon"
-        shift ;;
-    deepin)
-        config="deepin"
-        shift ;;
-    gnome)
-        config="gnome"
-        shift ;;
-    kde)
-        config="kde"
-        shift ;;
-    mate)
-        config="mate"
-        shift ;;
-    xfce)
-        config="xfce"
-        shift ;;
-    *)
-        _usage 1 ;;
-esac
-
-OPTS=$(getopt -o 'A:C:D:L:N:P:V:c:g:hl:o:w:v' --long 'confdir:,help' -n 'aui-mkiso' -- "$@")
-eval set -- "${OPTS}"
-
-[[ "$?" -eq 0 ]] || _usage 1
-unset OPTS
-
-while true; do
-    case "$1" in
-        '-C'|'--confdir')
-            confdir="$2"
-            shift 2 ;;
-        '-A'|'-D'|'-L'|'-N'|'-P'|'-V'|'-c'|'-g'|'-l'|'-o'|'-w')
-            options+="$1 $2 "
-            shift 2 ;;
-        '-h'|'--help')
-            options="-h"
-            shift
-            break ;;
-        '-v')
-            options+="-v "
-            shift ;;
-        '--')
-            shift
-            break ;;
-        *)
-            shift
-            echo "Invalid argument ${arg}"
-            _usage 1 ;;
-    esac
-done
-
-# Run the build script:
+# Launch the build script:
 eval "${confdir}/${config}/build.sh ${options}"
diff --git a/aui-mkpersistent b/aui-mkpersistent
--- a/aui-mkpersistent
+++ b/aui-mkpersistent
@@ -3,109 +3,213 @@
 set -e -u
 
 _usage () {
-    echo
-    echo 'aui-mkpersistent creates a live USB device'
-    echo 'with persistent storage'
-    echo
-    echo 'Usage:'
-    echo 'aui-mkpersistent <usb device> <iso image>'
-    echo
-    echo 'example:'
-    echo 'aui-mkpersistent /dev/sdc archuseriso-xfce-1130-x64.iso'
-    exit $1
+  echo
+  echo 'aui-mkpersistent, Live USB creation tool featuring persistent storage.'
+  echo
+  echo 'Command synopsis:'
+  echo 'aui-mkpersistent <usb device> <iso image> [options]'
+  echo
+  echo 'To get help run:'
+  echo 'aui-mkpersistent --help'
+  exit $1
 }
 
-# Check parameters
-[[ ${EUID} -eq 0 ]] || { echo 'This script must be run as root!'; exit 1; }
-[[ $# -eq 2 ]] || { echo 'Error: Invalid parameters!'; _usage 1; }
-[[ $(stat -c %t "$1" 2> /dev/null) -eq 8 ]] || { echo "Error: $1 is not a block device!"; _usage 1; }
-[[ $(lsblk -dnro rm "$1" 2> /dev/null) -eq 1 ]] || { echo "Error: $1 is not a removable block device!"; _usage 1; }
-[[ "$(lsblk -dnro tran "$1" 2> /dev/null)" == 'usb' ]] || { echo "Error: $1 is not a usb device!"; _usage 1; }
-grep -q "$1" /proc/mounts && { echo "Error: $1 appears in active mounts, unmount device before proceeding!"; exit 1; }
-[[ -f "$2" ]] || { echo "file $2 not found!"; _usage 1; }
-[[ $(file "$2" 2> /dev/null) =~ 'MBR boot sector' ]] || { echo "Error: $2 is not an iso image!"; _usage 1; }
+_help () {
+  echo
+  echo 'Archuseriso tool for creating a Live USB with persistent storage'
+  echo
+  echo 'Command synopsis:'
+  echo 'aui-mkpersistent <usb device> <iso image> [options]'
+  echo
+  echo 'Options:'
+  echo '-h, --help           command help'
+  echo '--encrypt            encrypt persistent partition'
+  echo
+  echo 'Example:'
+  echo 'aui-mkpersistent /dev/sdc archuseriso-xfce-1130-x64.iso --encrypt'
+  echo
+  exit $1
+}
 
-WD="${PWD}"
-usbdevice=$1
-isoname=$2
-devicesize=$(blockdev --getsize64 "${usbdevice}")
-isosize=$(stat -c %s "${isoname}")
-MINFREESPACE=1073741824 # 1GB
-ESPSIZE=786432 # 384MB
-workdir=auiwork
+_encrypt_mkluks () {
+  echo
+  echo 'Setting up encrypted partition, type in a passphrase of your choice...'
+  cryptsetup --label "${cryptlabel:=AUICRYPT}" --uuid "${cryptuuid:=$(uuidgen)}" -q luksFormat "${usbdevice}3" || \
+    { echo 'Encryption setup failed, exiting!'; exit 1; }
+  echo
+  echo 'LUKS encryption setup done! type in your passphrase to unlock device...'
+  cryptsetup open "${usbdevice}3" auicrypt || { echo 'Error: Could not unlock device! Exiting.'; exit 1; }
+  cowdevice=/dev/mapper/auicrypt
+}
 
-# Check usb device capacity
-[[ ${devicesize} -gt $(( isosize + MINFREESPACE )) ]] || { echo 'Storage capacity error!'; exit 1; }
+_encrypt_setup () {
+  echo 'Setting up encryption for persistence...'
+  mkdir "${WD}/${workdir}/"{overlay,squashfs}
+  mount "${WD}/${workdir}/iso/${install_dir}/x86_64/airootfs.sfs" "${WD}/${workdir}/squashfs" -o ro
+  mkdir "${WD}/${workdir}/usb3/persistent_${iso_label}/x86_64/workdir"
+  mount -t overlay airootper -o lowerdir="${WD}/${workdir}/squashfs",upperdir="${WD}/${workdir}/usb3/persistent_${iso_label}/x86_64/upperdir",workdir="${WD}/${workdir}/usb3/persistent_${iso_label}/x86_64/workdir" "${WD}/${workdir}/overlay"
+  mount "${WD}/${workdir}/usb2" "${WD}/${workdir}/overlay/boot" -o bind
+  cp "${WD}/${workdir}/iso/aui/mkinitcpio-archiso-encryption.conf" "${WD}/${workdir}/overlay/etc/"
+  ln -sf mkinitcpio-archiso-encryption.conf "${WD}/${workdir}/overlay/etc/mkinitcpio.conf"
+  arch-chroot "${WD}/${workdir}/overlay" mkinitcpio -P
+  sed -i "s|Storage$|& Encrypted|
+          s|overlay|cryptdevice=UUID=${cryptuuid}:auicrypt &|" \
+         "${WD}/${workdir}/overlay/boot/loader/entries/0aui_persistence-x86_64.conf"
+  umount "${WD}/${workdir}/overlay/boot" "${WD}/${workdir}/overlay" "/${WD}/${workdir}/squashfs"
+  sleep 1
+  rmdir "${WD}/${workdir}/overlay" "/${WD}/${workdir}/squashfs"
+}
 
-# Confim write
-read -r -n1 -p "Confirm write to $(lsblk -dnro model,size ${usbdevice}) (N/y)? "
-echo
-[[ "${REPLY}" =~ ^[Yy]$ ]] || { echo 'Operation canceled by user!';  exit 0; }
+_checks () {
+  [[ $# -eq 2 ]] || { echo 'Error: Invalid arguments!'; _usage 1; }
+  [[ ${EUID} -eq 0 ]] || { echo 'This script must be run as root!'; exit 1; }
 
-# Check & prepare working directory 
-for mountpoint in "${workdir}" "${workdir}/auiso" "${workdir}/auimnt"{3,4}; do
-  grep -q "${mountpoint}" /proc/mounts && \
-   { echo "Error: ${mountpoint} appears in active mounts, unmount before proceeding!";
-     exit 1; }
+  [[ $(stat -c %t "$1" 2> /dev/null) -eq 8 ]] || { echo "Error: $1 is not a block device!"; _usage 1; }
+  [[ $(lsblk -dnro rm "$1" 2> /dev/null) -eq 1 ]] || { echo "Error: $1 is not a removable block device!"; _usage 1; }
+  [[ "$(lsblk -dnro tran "$1" 2> /dev/null)" == 'usb' ]] || { echo "Error: $1 is not a usb device!"; _usage 1; }
+  grep -q "$1" /proc/mounts && { echo "Error: $1 appears in active mounts, unmount device before proceeding!"; exit 1; }
+  [[ -f "$2" ]] || { echo "file $2 not found!"; _usage 1; }
+  [[ $(file "$2" 2> /dev/null) =~ 'MBR boot sector' ]] || { echo "Error: $2 is not an iso image!"; _usage 1; }
+
+  usbdevice=$1
+  isoname=$2
+}
+
+_init () {
+  devicesize=$(blockdev --getsize64 "${usbdevice}")
+  ESPSIZE=786432 # 384 MiB
+  isosize=$(stat -c %s "${isoname}")
+  MINFREESPACE=1073741824 # 1 GiB
+  WD="${PWD}"
+  workdir=auiwork
+  # Check usb device capacity
+  [[ ${devicesize} -gt $(( isosize + MINFREESPACE )) ]] || { echo 'Storage capacity error!'; exit 1; }
+}
+
+_confirm_write () {
+  # Confim write
+  read -r -n1 -p "Confirm write to $(lsblk -dnro model,size ${usbdevice}) (N/y)? "
+  echo
+  [[ "${REPLY}" =~ ^[Yy]$ ]] || { echo 'Operation canceled by user!';  exit 0; }
+
+  # Check & prepare working directory
+  for mountpoint in "${workdir}" "${workdir}/"{iso,overlay,squashfs} "${workdir}/usb"{2,3}; do
+    grep -q "${mountpoint}" /proc/mounts && \
+     { echo "Error: ${mountpoint} appears in active mounts, unmount before proceeding!";
+       exit 1; }
+  done
+  for mountpoint in "${workdir}" "${workdir}/"{iso,overlay,squashfs} "${workdir}/usb"{2,3}; do
+    [[ -e "${WD}/${mountpoint}" ]] && \
+    { echo "Error: ${mountpoint} exists in working directory! Delete or rename before proceeding!";
+      exit 1; }
+  done
+  [[ -e /dev/mapper/auicrypt ]] && \
+    { echo 'Error: cryptsetup mapping /dev/mapper/auicrypt exists! cannot proceed.'; exit 1; }
+
+  mkdir -p "${WD}/${workdir}/iso" "${WD}/${workdir}/usb"{2,3}
+}
+
+_iso_copy () {
+  # Mount iso
+  echo 'Mounting iso...'
+  mount "${isoname}" "${WD}/${workdir}/iso" -o ro
+
+  # check iso
+  if [[ -f "${WD}/${workdir}/iso/aui/AUIDATA" ]]; then
+    eval $(grep cow_label "${WD}/${workdir}/iso/aui/AUIDATA")
+    eval $(grep iso_label "${WD}/${workdir}/iso/aui/AUIDATA")
+    eval $(grep install_dir "${WD}/${workdir}/iso/aui/AUIDATA")
+  else
+    echo "Error: ${isoname} is not a compatible image!"
+    umount "${WD}/${workdir}/iso"
+    rmdir "${WD}/${workdir}/usb"{2,3} "${WD}/${workdir}/iso" "${WD}/${workdir}"
+    _usage 1
+  fi
+
+  # Copy iso to usb
+  echo 'Writing image to USB device...'
+  flock "${usbdevice}" wipefs "${usbdevice}"* --all --force > /dev/null
+  cp -v "${isoname}" "${usbdevice}" || { echo 'Write failed!'; exit 1; }
+  sleep 1
+}
+
+_partitions () {
+  flock "${usbdevice}" sfdisk --delete "${usbdevice}" 2 -w always &> /dev/null
+  # Add ESP and persistent partitions, format ext4 partition with encryption support
+  sleep 1
+  echo 'Creating partitions...'
+  echo "$(( isosize / 512 )),${ESPSIZE},ef," | flock "${usbdevice}" sfdisk "${usbdevice}" --append -W always || \
+    { echo 'Creation of ESP partition failed!'; exit 1; }
+  sleep 1
+  echo "$(( isosize / 512 + ESPSIZE )),,83," | flock "${usbdevice}" sfdisk "${usbdevice}" --append -W always || \
+    { echo 'Creation of persistent partition failed!'; exit 1; }
+  sleep 1
+}
+
+_format () {
+  echo 'Formatting...'
+  flock "${usbdevice}2" mkfs.fat "${usbdevice}2" -F32 -n 'AUIESP' || \
+    { echo 'Formatting Persistent partition failed!'; exit 1; }
+  # Disable iso esp
+  cowdevice="${usbdevice}3"
+  [[ -n "${encryption:-}" ]] && _encrypt_mkluks
+  flock "${cowdevice}" mkfs.ext4 "${cowdevice}" -L "${cow_label}" -O encrypt || \
+    { echo 'Formatting Persistent partition failed!'; exit 1; }
+}
+
+_mount () {
+  # Mount usb device
+  echo 'Mounting usb device...'
+  mount "${usbdevice}2" "${WD}/${workdir}/usb2"
+  mount "${cowdevice}" "${WD}/${workdir}/usb3"
+}
+
+_persistence () {
+  # Persistence setup
+  echo 'Setting up persistence...'
+  cp -LrT "${WD}/${workdir}/iso/aui/esp" "${WD}/${workdir}/usb2/"
+  cp -r "${WD}/${workdir}/iso/aui/loader" "${WD}/${workdir}/usb2/"
+  cp -a "${WD}/${workdir}/iso/aui/"persistent_* "${WD}/${workdir}/usb3/"
+  cp "${WD}/${workdir}/iso/aui/refind.conf" "${WD}/${workdir}/usb2/EFI/BOOT/"
+  cp "${WD}/${workdir}/iso/aui/AUIDATA" "${WD}/${workdir}/usb3/"
+  [[ -n "${encryption:-}" ]] && _encrypt_setup || true
+}
+
+_finalize () {
+  # Clean up
+  umount "${WD}/${workdir}/usb"{2,3} "${WD}/${workdir}/iso"
+  rmdir "${WD}/${workdir}/usb"{2,3} "${WD}/${workdir}/iso" "${WD}/${workdir}"
+  [[ -n "${encryption:-}" ]] && cryptsetup close auicrypt || true
+}
+
+# arguments
+OPTS=$(getopt -o 'h' --long 'encrypt,help' -n 'aui-mkpersistent' -- "$@")
+[[ $? -eq 0 ]] || _usage 1
+eval set -- "${OPTS}"
+unset OPTS
+[[ $# -eq 1 ]] && _usage 1
+
+while true; do
+  case "$1" in
+    '-h'|'--help')
+      _help 0 ;;
+    '--encrypt')
+      encryption=yes
+      shift ;;
+    '--')
+      shift
+      break ;;
+  esac
 done
-for mountpoint in "${workdir}" "${workdir}/auiso" "${workdir}/auimnt"{3,4}; do
-  [[ -e "${WD}/${mountpoint}" ]] && \
-  { echo "Error: ${mountpoint} exists in working directory! Delete or rename before proceeding!";
-    exit 1; }
-done
 
-mkdir -p "${WD}/${workdir}/auiso" "${WD}/${workdir}/auimnt"{3,4}
-
-# Mount archuseriso image
-echo 'Mounting iso...'
-mount "${isoname}" "${WD}/${workdir}/auiso" -o ro
-
-# check archuseriso image
-if [[ -f "${WD}/${workdir}/auiso/aui/AUIDATA" ]]; then
-  eval $(grep cow_label "${WD}/${workdir}/auiso/aui/AUIDATA")
-else
-  echo "Error: ${isoname} is not a compatible image!"
-  umount "${WD}/${workdir}/auiso"
-  rmdir "${WD}/${workdir}/auimnt"{3,4} "${WD}/${workdir}/auiso" "${WD}/${workdir}"
-  _usage 1
-fi
-
-# Copy iso to usb 
-echo 'Writing image to USB device...'
-flock "${usbdevice}" wipefs "${usbdevice}"* --all --force > /dev/null
-cp -v "${isoname}" "${usbdevice}" || { echo 'Write failed!'; exit 1; }
-
-# Add ESP and persistent partitions, format ext4 partition with encryption support
-echo 'Creating partitions...'
-echo "$(( isosize / 512 )),${ESPSIZE},ef," | flock "${usbdevice}" sfdisk "${usbdevice}" --append -W always > /dev/null || \
-  { echo 'Creation of ESP partition failed!'; exit 1; }
-echo "$(( isosize / 512 + ESPSIZE )),,83," | flock "${usbdevice}" sfdisk "${usbdevice}" --append -W always > /dev/null || \
-  { echo 'Creation of persistent partition failed!'; exit 1; }
-echo 'Formatting...'
-flock "${usbdevice}" mkfs.fat "${usbdevice}3" -F32 -n 'AUIESP' > /dev/null || \
-  { echo 'Formatting Persistent partition failed!'; exit 1; }
-flock "${usbdevice}" mkfs.ext4 -q -L "${cow_label}" -O encrypt "${usbdevice}4" > /dev/null || \
-  { echo 'Formatting Persistent partition failed!'; exit 1; }
-
-# Mount usb device
-echo 'Mounting usb device...'
-mount "${usbdevice}3" "${WD}/${workdir}/auimnt3"
-mount "${usbdevice}4" "${WD}/${workdir}/auimnt4"
-
-# Persistence setup
-echo 'Setting up persistence...'
-cp -LrT "${WD}/${workdir}/auiso/aui/esp" "${WD}/${workdir}/auimnt3/"
-cp -r "${WD}/${workdir}/auiso/aui/loader" "${WD}/${workdir}/auimnt3/"
-cp -a "${WD}/${workdir}/auiso/aui/"persistent_* "${WD}/${workdir}/auimnt4/"
-cp "${WD}/${workdir}/auiso/aui/refind.conf" "${WD}/${workdir}/auimnt3/EFI/BOOT/" 
-cp "${WD}/${workdir}/auiso/aui/AUIDATA" "${WD}/${workdir}/auimnt4/"
-
-# Disable iso esp
-flock "${usbdevice}" sfdisk "${usbdevice}" 2 --part-type 0 &> /dev/null
-
-# Clean up
-umount "${WD}/${workdir}/auimnt"{3,4} "${WD}/${workdir}/auiso"
-rmdir "${WD}/${workdir}/auimnt"{3,4} "${WD}/${workdir}/auiso" "${WD}/${workdir}"
-
+_checks "$@"
+_init
+_confirm_write
+_iso_copy
+_partitions
+_format
+_mount
+_persistence
+_finalize
 
 echo 'Done!'
diff --git a/aui-mkusb b/aui-mkusb
--- a/aui-mkusb
+++ b/aui-mkusb
@@ -3,20 +3,53 @@
 set -e -u
 
 _usage () {
-    echo
-    echo 'aui-mkusb creates a live USB device'
-    echo
-    echo 'Usage:'
-    echo 'aui-mkusb <usb device> <iso image>'
-    echo
-    echo 'example:'
-    echo 'aui-mkusb /dev/sdc archuseriso-xfce-1130-x64.iso'
-    exit $1
+  echo
+  echo 'aui-mkusb, Live USB creation tool.'
+  echo
+  echo 'Command synopsis:'
+  echo 'aui-mkusb <usb device> <iso image> [options]'
+  echo
+  echo 'To get help run:'
+  echo 'aui-mkusb --help'
+  exit $1
 }
 
-# check parameters
+_help () {
+  echo
+  echo 'Archuseriso tool for creating a Live USB'
+  echo
+  echo 'Command synopsis:'
+  echo 'aui-mkusb <usb device> <iso image> [options]'
+  echo
+  echo 'Options:'
+  echo '-h, --help           command help'
+  echo
+  echo 'Example:'
+  echo 'aui-mkusb /dev/sdc archuseriso-xfce-1130-x64.iso'
+  echo
+  exit $1
+}
+
+# check arguments
+OPTS=$(getopt -o 'h' --long 'help' -n 'aui-mkusb' -- "$@")
+[[ $? -eq 0 ]] || _usage 1
+eval set -- "${OPTS}"
+unset OPTS
+[[ $# -eq 1 ]] && _usage 1
+
+while true; do
+  case "$1" in
+    '-h'|'--help')
+      _help 0 ;;
+    '--')
+      shift
+      break ;;
+  esac
+done
+
+[[ $# -eq 2 ]] || { echo 'Error: invalid arguments!'; _usage 1; }
 [[ ${EUID} -eq 0 ]] || { echo 'This script must be run as root!'; exit 1; }
-[[ $# -eq 2 ]] || { echo 'Error: Invalid parameters!'; _usage 1; }
+
 [[ $(stat -c %t "$1" 2> /dev/null) -eq 8 ]] || { echo "Error: $1 is not a block device!"; _usage 1; }
 [[ $(lsblk -dnro rm "$1" 2> /dev/null) -eq 1 ]] || { echo "Error: $1 is not a removable block device!"; _usage 1; }
 [[ "$(lsblk -dnro tran "$1" 2> /dev/null)" == 'usb' ]] || { echo "Error: $1 is not a usb device!"; _usage 1; }
@@ -36,6 +69,6 @@ isosize=$(stat -c %s "${isoname}")
 read -r -n1 -p "Confirm write to $(lsblk -dnro model,size ${usbdevice}) (N/y)? "
 echo
 [[ "${REPLY}" =~ ^[Yy]$ ]] || { echo 'Operation canceled by user!';  exit 0; }
-echo 'Writing to USB device...'
+echo 'Writing image to USB device...'
 cp -v "${isoname}" "${usbdevice}" || { echo 'Write failed!'; exit 1; }
 echo 'Done!'
