aui-mkiso, aui-mkusb, aui-mkpersistent

diff --git a/aui-mkusb b/aui-mkusb
--- a/aui-mkusb
+++ b/aui-mkusb
@@ -1,20 +1,26 @@
 #!/bin/bash
 
+set -e -u
+
 _usage () {
     echo
+    echo 'aui-mkusb creates a live USB device'
+    echo
     echo 'Usage:'
-    echo 'mkauipers <usb device> <iso image>'
+    echo 'aui-mkusb <usb device> <iso image>'
     echo
     echo 'example:'
-    echo 'mkauipers /dev/sdc archuseriso-xfce-1030-x64.iso'
+    echo 'aui-mkusb /dev/sdc archuseriso-xfce-1130-x64.iso'
     exit $1
 }
 
+# check parameters
 [[ ${EUID} -eq 0 ]] || { echo 'This script must be run as root!'; exit 1; }
 [[ $# -eq 2 ]] || { echo 'Error: Invalid parameters!'; _usage 1; }
 [[ $(stat -c %t "$1" 2> /dev/null) -eq 8 ]] || { echo "Error: $1 is not a block device!"; _usage 1; }
 [[ $(lsblk -dnro rm "$1" 2> /dev/null) -eq 1 ]] || { echo "Error: $1 is not a removable block device!"; _usage 1; }
 [[ "$(lsblk -dnro tran "$1" 2> /dev/null)" == 'usb' ]] || { echo "Error: $1 is not a usb device!"; _usage 1; }
+grep -q "$1" /proc/mounts && { echo "Error: $1 appears in active mounts, unmount device before proceeding!"; exit 1; }
 [[ -f "$2" ]] || { echo "file $2 not found!"; _usage 1; }
 [[ $(file "$2" 2> /dev/null) =~ 'MBR boot sector' ]] || { echo "Error: $2 is not an iso image!"; _usage 1; }
 
@@ -23,18 +29,13 @@ isoname=$2
 devicesize=$(blockdev --getsize64 "${usbdevice}")
 isosize=$(stat -c %s "${isoname}")
 
-[[ ${devicesize} -gt $(( isosize + 1073741824 )) ]] || { echo 'Storage capacity error!'; exit 1; }
+# Check usb device capacity
+[[ ${devicesize} -gt ${isosize} ]] || { echo 'Storage capacity error!'; exit 1; }
 
+# Confirm write
 read -r -n1 -p "Confirm write to $(lsblk -dnro model,size ${usbdevice}) (N/y)? "
 echo
 [[ "${REPLY}" =~ ^[Yy]$ ]] || { echo 'Operation canceled by user!';  exit 0; }
-
 echo 'Writing to USB device...'
 cp -v "${isoname}" "${usbdevice}" || { echo 'Write failed!'; exit 1; }
-echo 'Creating persistent partition...'
-echo "$(( isosize / 512 + 1 )),,83," | flock "${usbdevice}" sfdisk "${usbdevice}" --append &> /dev/null || \
-    { echo 'Creation of persistent partition failed!'; exit 1; }
-echo 'Formatting...'
-mkfs.ext4 -L AUIPERS -O encrypt "${usbdevice}3" &> /dev/null || \
-    { echo 'Formatting Persistent partition failed!'; exit 1; }
 echo 'Done!'
