aui-run options modification

diff --git a/archuseriso/aui-run b/archuseriso/aui-run
--- a/archuseriso/aui-run
+++ b/archuseriso/aui-run
@@ -26,21 +26,21 @@ Usage:
     aui-run [options]
 
 Options:
-    -a                   set accessibility support using brltty (console profile only)
-    -b, --bios           set boot type to 'BIOS' (default)
-    -d, --usb [device]   set usb block device to boot from
-    -h, --help           print help
-    -i, --iso [image]    image to boot into
-    -k, --iso-hd         set image type to hard disk instead of optical disc
-    -s, --sb             use Secure Boot (only relevant when using UEFI)
-    -u, --uefi           set boot type to 'UEFI'
-    -v                   use VNC display (instead of default SDL)
+    -a                      set accessibility support using brltty (console profile only)
+    -b, --bios              set boot type to 'BIOS' (default)
+    -d, --device [device]   set usb block device to boot from
+    -h, --help              print help
+    -i, --iso [image]       image to boot into
+    --hd                    set image type to hard disk instead of optical disc
+    -s, --sb                use Secure Boot (only relevant when using UEFI)
+    -u, --uefi              set boot type to 'UEFI'
+    -v, --vnc               use VNC display (instead of default SDL)
 
 Examples:
     Run an image using UEFI:
     $ aui-run --uefi --iso aui-xfce-linux_5_10_5-0108-x64.iso 
     Run a bootable usb drive using UEFI:
-    $ sudo aui-run --uefi --usb /dev/sdc
+    $ sudo aui-run --uefi --device /dev/sdc
 EOF
     printf '%s' "${usagetext}"
 }
@@ -84,12 +84,16 @@ _checks() {
         echo "Error: ${device} is not a usb device!"
         exit 1
     fi
+    if ! pacman -Q qemu &> /dev/null; then
+        echo 'qemu not installed, aborting!'
+        exit 0
+    fi
 }
 
 _run() {
     if [[ "$boot_type" == 'uefi' ]]; then
         if ! pacman -Q edk2-ovmf &> /dev/null; then
-            echo 'edk2-ovmf package not installed, aborting!'
+            echo 'edk2-ovmf not installed, aborting!'
             exit 0
         fi
         copy_ovmf_vars
@@ -164,8 +168,8 @@ secure_boot='off'
 working_dir="$(mktemp -dt auirun.XXXXXXXX)"
 trap cleanup_working_dir EXIT
 
-OPTS=$(getopt -o     'abd:hi:ksuv' \
-	      --long 'bios,help,iso:,iso-hd,sb,uefi,usb:,vnc' \
+OPTS=$(getopt -o     'abd:hi:suv' \
+	      --long 'bios,device:,hd,help,iso:,sb,uefi,vnc' \
 	      -n 'aui-run' -- "$@")
 [[ $? -eq 0 ]] || { print_help; exit 1; }
 eval set -- "${OPTS}"
@@ -181,7 +185,7 @@ while true; do
             '-b'|'--bios')
                 boot_type='bios'
                 shift ;;
-            '-d'|'--usb')
+            '-d'|'--device')
                 usbdrive='yes'
                 device="${2}"
                 shift 2 ;;
@@ -193,7 +197,7 @@ while true; do
                 isoimage='yes'
                 image="${2}"
                 shift 2 ;;
-            '-k'|'--iso-hd')
+            '--hd')
                 mediatype='hd'
                 shift ;;
             '-s'|'--sb')
