new option for zfs support
New aui-mkiso '--zfssupport' command option for building
zfs userspace utilities and modules against current linux
kernel version.
Packages 'zfs-utils', 'zfs-linux' and 'zfs-linux-headers'
are built then added to the the iso image build.utility for building zfs packages

diff --git a/archuseriso/aui-mkiso b/archuseriso/aui-mkiso
--- a/archuseriso/aui-mkiso
+++ b/archuseriso/aui-mkiso
@@ -3,8 +3,10 @@
 set -e -u
 
 confdir=/usr/share/archiso/configs
-config=
-options=
+config=""
+options=""
+SCRIPTUSER="${SUDO_USER:-}"
+WD="$(pwd)"
 
 _usage () {
         echo
@@ -42,6 +44,8 @@ _help () {
         echo '                                  Nvidia dGPU configured for PRIME render offload'
         echo '--pkgdir <path>                   User directory containing package files to install'
         echo '-v, --verbose                     Verbose mode'
+        echo '--zfssupport                      Build userspace utilities and kernel modules packages for the'
+        echo '                                  Zettabyte File System. Then build the iso image with zfs support.'
         echo
         echo 'ISO config list:'
         echo 'console, cinnamon, deepin, gnome, i3, kde, lxqt, mate, xfce'
@@ -61,8 +65,97 @@ _help () {
         exit ${1}
 }
 
+_build_zfs_packages () {
+        local _auiwork="${WD}"/auiwork$(openssl rand -hex 4)
+        local _ar64="${_auiwork}/archroot64"
+        local _linuxversion _zfspackages _zfssha256sum _zfssources _zfsversion
+        local _ZFSPUBKEY="6AD860EED4598027"
+        local _KEYSERVER="ha.pool.sks-keyservers.net"
+
+        # Retrieve ZFS on Linux public key
+        if ! sudo --user "${SCRIPTUSER}" gpg --list-public-keys "${_ZFSPUBKEY}" &> /dev/null; then
+                echo
+                read -r -n1 -p 'Retreive missing ZFS on Linux public key (N/y)? '
+                echo
+                if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
+                        echo 'Operation canceled by user!'
+                        exit 0
+                fi
+                if ! sudo --user "${SCRIPTUSER}" gpg --keyserver "${_KEYSERVER}" --recv "${_ZFSPUBKEY}"; then
+                        echo
+                        echo "Retreiving ZFS public key ${_ZFSPUBKEY} failed, aborting!"
+                        echo
+                fi
+        fi
+
+        mkdir -p "${WD}/work/pkgdir"
+        mkdir -p "${_ar64}"
+        if ! pacman -Q devtools &> /dev/null; then
+                echo 'devtools package not installed, aborting!'
+                exit 0
+        fi
+        if ! pacman -Q pacman-contrib &> /dev/null; then
+                echo 'pacman-contrib package not installed, aborting!'
+                exit 0
+        fi
+        _zfssources=($(curl --silent --retry 3 --retry-connrefused --fail \
+                       https://api.github.com/repos/openzfs/zfs/releases/latest | \
+                       grep browser_download_url | cut -d':' -f2- | sed 's/"//g'))
+        _zfsversion="${_zfssources[0]%/zfs-*}"
+        _zfsversion="${_zfsversion#*-}"
+        for _zfslink in "${_zfssources[@]}"; do
+                if [[ "${_zfslink}" =~ 'sha256.asc' ]]; then
+                       _zfssha256sum=$(eval curl --silent --retry 3 --retry-connrefused --fail -L "${_zfslink}" | \
+                         grep '\.tar\.gz$' | cut -d' ' -f1)
+                       break
+                fi
+        done
+        if [[ -z "${_zfsversion}" || -z "${_zfssha256sum}" ]]; then
+                echo 'Retrieving ZFS data failed, aborting!'
+                exit 0
+        fi
+        LC_ALL=C mkarchroot -c /var/cache/pacman/pkg "${_ar64}"/root base linux linux-headers base-devel
+        _linuxversion=$(pacman --sysroot "${_ar64}/root" -Q linux | cut -d' ' -f2)
+        cp -arT "${confdir}/${config}/aui/zfsonlinux" "${_auiwork}/zfsonlinux"
+        sed -i "s/%ZFSVERSION%/${_zfsversion}/
+                s/%LINUXVERSION%/${_linuxversion}/
+                s/%SHA256SUM%/${_zfssha256sum}/" \
+                "${_auiwork}/zfsonlinux/zfs-utils/PKGBUILD" \
+                "${_auiwork}/zfsonlinux/zfs-linux/PKGBUILD"
+        cd "${_auiwork}/zfsonlinux/zfs-utils/"
+        for _zfslink in "${_zfssources[@]}"; do
+                if [[ "${_zfslink}" =~ '.tar.gz'$ ]]; then
+                       curl --silent --retry 3 --retry-connrefused --fail -L "${_zfslink}" -O
+                       curl --silent --retry 3 --retry-connrefused --fail -L "${_zfslink}".asc -O
+                       break
+                fi
+        done
+        cp -a zfs-*.tar.gz{,.asc} ../zfs-linux 
+        chown -R "${SCRIPTUSER}": "${_auiwork}/zfsonlinux"
+        sudo --user "${SCRIPTUSER}" makepkg --geninteg >> PKGBUILD
+        sudo --user "${SCRIPTUSER}" updpkgsums
+        cd "${_auiwork}/zfsonlinux/zfs-linux/"
+        sudo --user "${SCRIPTUSER}" makepkg --geninteg >> PKGBUILD
+        sudo --user "${SCRIPTUSER}" updpkgsums
+        cd "${_auiwork}/zfsonlinux/zfs-utils/"
+        LC_ALL=C sudo --user "${SCRIPTUSER}" \
+        makechrootpkg -r "${_ar64}" -u -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
+        _zfspackages=($(find "${_auiwork}/zfsonlinux/" | grep -e '\.pkg\.tar\.zst$' -e '\.pkg\.tar\.xz$'))
+        cd "${_auiwork}/zfsonlinux/zfs-linux/"
+        LC_ALL=C sudo --user "${SCRIPTUSER}" \
+        makechrootpkg -r "${_ar64}" -u -I "${_zfspackages[0]}" -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
+        _zfspackages=($(find "${_auiwork}/zfsonlinux/" | grep -e '\.pkg\.tar\.zst$' -e '\.pkg\.tar\.xz$'))
+        if [[ -n "${AUI_USERPKGDIR:-}" ]]; then
+                cp "${_zfspackages[@]}" "${AUI_USERPKGDIR}"
+        else
+                cp "${_zfspackages[@]}" "${WD}/work/pkgdir"
+                export AUI_USERPKGDIR="${WD}/work/pkgdir"
+        fi
+        rm -r "${_auiwork}"
+}
+
 OPTS=$(getopt -o 'A:C:D:L:N:P:V:c:g:hl:o:w:v' -l 'addi3wm,addpkg:,confdir:,configs-dir:,embeddir:,help' \
-       -l 'language:,nvidia,optimus,pkgdir:,verbose' -n 'aui-mkiso' -- "$@")
+       -l 'language:,nvidia,optimus,pkgdir:,verbose,zfssupport' -n 'aui-mkiso' -- "$@")
 [[ $? -eq 0 ]] || _usage 1
 eval set -- "${OPTS}"
 unset OPTS
@@ -107,6 +200,10 @@ while true; do
                 '-v'|'verbose')
                         options+="-v "
                         shift ;;
+                '--zfssupport')
+                        AUI_ZFSSUPPORT="yes"
+                        AUI_ISONAME+=(zfs)
+                        shift ;;
                 '--')
                         shift
                         break ;;
@@ -143,7 +240,9 @@ case $1 in
         cinnamon | deepin | gnome | i3 | kde | lxqt | mate | xfce)
                 config=$1 ;;
         console)
+                echo
                 echo 'Console iso build reminder, some options may be ignored!'
+                sleep 3
                 config=$1 ;;
         *)
                 _usage 1 ;;
@@ -158,7 +257,20 @@ if [[ ! "${options}" =~ '-h' && ${EUID} -ne 0 ]]; then
 fi
 
 if [[ -d "work" ]]; then
-        echo \'work\'' directory exists!'
+        echo \'work\'' directory exists, aborting!'
+        exit 0
+fi
+
+if [[ -n "${AUI_ZFSSUPPORT:-}" ]]; then
+        if [[ "${SCRIPTUSER}" = 'root' || -z "${SUDO_USER:-}" ]]; then
+                echo
+                echo 'Option for ZFS support:'
+                echo 'The script must be run from a _user session_ using sudo!'
+                echo 'Aborting...'
+                exit 0
+        fi
+        _build_zfs_packages
+        cd "${WD}"
 fi
 
 # Launch the build script:
