use udevadm for locking block device

diff --git a/archuseriso/aui-mkinstall b/archuseriso/aui-mkinstall
--- a/archuseriso/aui-mkinstall
+++ b/archuseriso/aui-mkinstall
@@ -97,8 +97,8 @@ _cleanup() {
             fi
             [[ "$(zfs get mounted "${zroot}/ROOT/default" -H -o value)" == "yes" ]] && \
                   zfs unmount "${zroot}/ROOT/default"
-                                                                                                                            zpool export "${zroot}"
-                                                                                                                            sleep 5
+            zpool export "${zroot}"
+            sleep 3
         fi
     fi
     for _workdir in ${_workdirs[*]}; do
@@ -434,36 +434,39 @@ _partitions() {
     fi
 
     # Wipe drive
-    flock -- "${usb_device}" wipefs --all --force -- "${usb_device}"* > /dev/null
-    sleep 5
+    udevadm lock --device="${usb_device}" -- wipefs --all --force -- "${usb_device}"* > /dev/null
+    sleep 3
     partprobe -- "${usb_device}"
     echo
 
     # New gpt partition table
     _msg_info "Drive partitions"
     _msg_info "New gpt label"
-    if ! echo 'label: gpt' | sfdisk -W always -- "${usb_device}" > /dev/null; then
+    if ! echo 'label: gpt' | udevadm lock --device="${usb_device}" -- \
+            sfdisk -W always -- "${usb_device}" > /dev/null; then
         echo 'Failed to create new gpt partition table!'
         exit 1
     fi
-    sleep 5
+    sleep 3
     partprobe -- "${usb_device}"
 
     # partition #1 boot & efi partition
     _msg_info "partition #1, boot partition: $(( _size_esp_part / 1024 / 1024 )) MiB"
-    if ! echo "$(( _start_esp_part )),$(( _sectors_esp_part )),${_part_type_msft}," | sfdisk --append -W always -- "${usb_device}" > /dev/null; then
+    if ! echo "$(( _start_esp_part )),$(( _sectors_esp_part )),${_part_type_msft}," | \
+            udevadm lock --device="${usb_device}" -- sfdisk --append -W always -- "${usb_device}" > /dev/null; then
         echo 'Failed to create new partition layout!'
         exit 1
     fi
-    sleep 5
+    sleep 3
 
     # partition #2 root partition
     _msg_info "partition #2, root partition: $(( _size_rw_part / 1024 / 1024 )) MiB"
-    if ! echo "$(( _start_rw_part )),${_sectors_rw_part:-},${_part_type_linux_or_solaris}," | sfdisk --append -W always -- "${usb_device}" > /dev/null; then
+    if ! echo "$(( _start_rw_part )),${_sectors_rw_part:-},${_part_type_linux_or_solaris}," | \
+            udevadm lock --device="${usb_device}" -- sfdisk --append -W always -- "${usb_device}" > /dev/null; then
         echo 'Failed to create new partition layout!'
         exit 1
     fi
-    sleep 5
+    sleep 3
 
     partprobe -- "${usb_device}"
     _msg_info "Done!"
@@ -471,7 +474,8 @@ _partitions() {
 
 _format_btrfs() {
     _msg_info "partition #2: type Btrfs, label ${root_label}"
-    if ! flock -- "${root_device}" mkfs.btrfs -L "${root_label}" -- "${root_device}" > /dev/null; then
+    if ! udevadm lock --device="${root_device}" -- \
+            mkfs.btrfs -L "${root_label}" -- "${root_device}" > /dev/null; then
         echo 'Format failed!'
         exit 1
     fi
@@ -479,7 +483,8 @@ _format_btrfs() {
 
 _format_f2fs() {
     _msg_info "partition #2: type F2FS, label ${root_label}"
-    if ! flock -- "${root_device}" mkfs.f2fs -l "${root_label}" -O encrypt,extra_attr,compression -- "${root_device}" > /dev/null; then
+    if ! udevadm lock --device="${root_device}" -- \
+            mkfs.f2fs -l "${root_label}" -O encrypt,extra_attr,compression -- "${root_device}" > /dev/null; then
         echo 'Format failed!'
         exit 1
     fi
@@ -487,7 +492,8 @@ _format_f2fs() {
 
 _format_ext4() {
     _msg_info "partition #2: type Ext4, label ${root_label}"
-    if ! flock -- "${root_device}" mkfs.ext4 -L "${root_label}" -O encrypt -q -- "${root_device}" > /dev/null; then
+    if ! udevadm lock --device="${root_device}" -- \
+            mkfs.ext4 -L "${root_label}" -O encrypt -q -- "${root_device}" > /dev/null; then
         echo 'Format failed!'
         exit 1
     fi
@@ -503,21 +509,21 @@ _format_zfs() {
     zroot="zroot${aui_suffix,,}"
 
     _msg_info "partition #2: type ZFS, pool name ${root_label}"
-    if ! flock -- "${root_device}"                   \
-        zpool create -f -o ashift=12                \
-        -O acltype=posixacl         \
-        -O relatime=on              \
-        -O xattr=sa                 \
-        -O dnodesize=legacy         \
-        -O normalization=formD      \
-        -O mountpoint=none          \
-        -O canmount=off             \
-        -O devices=off              \
-        -O compression=lz4          \
-        -R "${WD}/${workdir}/usbrw" \
-        "${zroot}" "${partuuid}" > /dev/null; then
-            echo 'Format failed!'
-            exit 1
+    if ! udevadm lock --device="${root_device}" --  \
+            zpool create -f -o ashift=12 \
+            -O acltype=posixacl         \
+            -O relatime=on              \
+            -O xattr=sa                 \
+            -O dnodesize=legacy         \
+            -O normalization=formD      \
+            -O mountpoint=none          \
+            -O canmount=off             \
+            -O devices=off              \
+            -O compression=lz4          \
+            -R "${WD}/${workdir}/usbrw" \
+            "${zroot}" "${partuuid}" > /dev/null; then
+        echo 'Format failed!'
+        exit 1
     fi
     zfs create -o mountpoint=none "${zroot}/data"
     zfs create -o mountpoint=none "${zroot}/ROOT"
@@ -526,14 +532,15 @@ _format_zfs() {
     zfs create -o mountpoint=/root "${zroot}/data/root"
     zpool set bootfs="${zroot}/ROOT/default" "${zroot}"
     zpool export "${zroot}"
-    sleep 5
+    sleep 3
 }
 
 _format() {
     echo
     _msg_info "Format partitions"
     _msg_info "partition #1: type FAT, label ${esp_label}"
-    if ! flock -- "${usb_device}1" mkfs.fat -F32 -n "${esp_label}" -- "${usb_device}1" &> /dev/null; then
+    if ! udevadm lock --device="${usb_device}1" -- \
+            mkfs.fat -F32 -n "${esp_label}" -- "${usb_device}1" &> /dev/null; then
         echo 'Format failed!'
         exit 1
     fi
@@ -564,7 +571,7 @@ _mount() {
             btrfs subvolume create -- "${WD}/${workdir}/usbrw/${btrfs_subvol_root}" > /dev/null
             btrfs subvolume create -- "${WD}/${workdir}/usbrw/${btrfs_subvol_home}" > /dev/null
             umount "${WD}/${workdir}/usbrw"
-            sleep 5
+            sleep 3
             mount -o "${root_flags}" -- "${root_device}" "${WD}/${workdir}/usbrw"
             mkdir -p -- "${WD}/${workdir}/usbrw/home"
             mount -o subvol="${btrfs_subvol_home}" -- "${root_device}" "${WD}/${workdir}/usbrw/home"
@@ -834,7 +841,8 @@ _biosbootloader() {
         echo 'Boot loader installation failed!'
         exit 1
      fi
-     if ! sfdisk --part-attrs "${usb_device}" 1 LegacyBIOSBootable &> /dev/null; then
+     if ! udevadm lock --device="${usb_device}" -- \
+             sfdisk --part-attrs "${usb_device}" 1 LegacyBIOSBootable &> /dev/null; then
          echo 'Boot loader installation failed!'
          exit 1
      fi
